# Get all users

GET http://localhost:9080/heroes/api/users

###

# Get single user

GET http://localhost:9080/heroes/api/users/d9f823f4-f057-4f18-aeb7-b6654bc3d314

###

# Get single user. Not existing.

GET http://localhost:9080/heroes/api/users/d9f823f4-f057-4f18-aeb7-b6654bc3d315

###

# Put user

PUT http://localhost:9080/heroes/api/users/d9f823f4-f057-4f18-aeb7-b6654bc3d314
Content-Type: application/json

{
  "name": "Blazej",
  "accountCreation": "2012-04-23"
}

###

# Patch user

PATCH http://localhost:9080/heroes/api/users/d9f823f4-f057-4f18-aeb7-b6654bc3d314
Content-Type: application/json

{
  "name": "Blazej2",
  "accountCreation": "2010-01-11"
}

###

# Delete user

DELETE http://localhost:9080/heroes/api/users/d9f823f4-f057-4f18-aeb7-b6654bc3d310

###

# Get single user avatar

GET http://localhost:9080/heroes/api/users/d9f823f4-f057-4f18-aeb7-b6654bc3d310/avatar

###

# Create user avatar.

PUT http://localhost:9080/heroes/api/users/d9f823f4-f057-4f18-aeb7-b6654bc3d310/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="crag-hack.png"

< src/main/resources/stenka/marcin/heroes/configuration/avatar/crag-hack.png
--boundary--

###

# Delete user avatar

DELETE http://localhost:9080/heroes/api/users/d9f823f4-f057-4f18-aeb7-b6654bc3d310/avatar

###

# Update user avatar.

PATCH http://localhost:9080/heroes/api/users/d9f823f4-f057-4f18-aeb7-b6654bc3d311/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="solmyr.png"

< src/main/resources/stenka/marcin/heroes/configuration/avatar/solmyr.png
--boundary--

###

# Get all fractions

GET http://localhost:9080/heroes/api/fractions/
Authorization: Basic T3NrYXI6T3NrYXI=

###

# Get single fraction

GET http://localhost:9080/heroes/api/fractions/d9f823f4-f057-4f18-aeb7-b6654bc3d330

###

# Get fraction units

GET http://localhost:9080/heroes/api/fractions/d9f823f4-f057-4f18-aeb7-b6654bc3d330/units

###

# Put fraction

PUT http://localhost:9080/heroes/api/fractions/d9f823f4-f057-4f18-aeb7-b6654bc3d332
Content-Type: application/json

{
  "name": "Stronghold",
  "fractionType": "NEUTRAL"
}

###

# Delete fraction

DELETE http://localhost:9080/heroes/api/fractions/d9f823f4-f057-4f18-aeb7-b6654bc3d330

###

# Get all units

GET http://localhost:9080/heroes/api/units

###

# Get single unit
// @no-cookie-jar
GET http://localhost:9080/heroes/api/fractions/d9f823f4-f057-4f18-aeb7-b6654bc3d330/units/d9f823f4-f057-4f18-aeb7-b6654bc3d320
Authorization: Basic TWFyY2luOk1hcmNpbg==
###

# Get user units

GET http://localhost:9080/heroes/api/users/d9f823f4-f057-4f18-aeb7-b6654bc3d311/units/

###

# Put unit

PUT http://localhost:9080/heroes/api/fractions/d9f823f4-f057-4f18-aeb7-b6654bc3d330/units/d9f823f4-f057-4f18-aeb7-b6654bc3d324
Content-Type: application/json

{
  "name": "Behemoth",
  "quantity": 1,
  "user": "d9f823f4-f057-4f18-aeb7-b6654bc3d311"
}

###

# Patch unit

PATCH http://localhost:9080/heroes/api/fractions/d9f823f4-f057-4f18-aeb7-b6654bc3d330/units/d9f823f4-f057-4f18-aeb7-b6654bc3d324
Content-Type: application/json

{
  "name": "Ancient Behemoth",
  "quantity": "2"
}

###

# Delete unit

DELETE http://localhost:9080/heroes/api/fractions/d9f823f4-f057-4f18-aeb7-b6654bc3d330/units/d9f823f4-f057-4f18-aeb7-b6654bc3d324

###